### ISSUE TITLE
unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/stock-pattern#4]
Hello Benny,

I was testing this repo, giving the following error.

saurabhgarg@MacBook-Pro src % python3 init.py --f daily.csv

    Enter a number to select a pattern.

    1. Bullish VCP (Volatility Contraction pattern)
    2. Bearish VCP
    3. Double Bottom (Bullish)
    4. Double Top (Bearish)
    5. Head and Shoulder
    6. Reverse Head and Shoulder
    7. Pennant (Triangle - Symetrical, Ascending, Descending, Wedges)
    > 1
Scanning stocks. Press Ctrl - C to exit
unsupported operand type(s) for |: 'type' and 'type'
Traceback (most recent call last):
  File "/Users/saurabhgarg/shivshakti/stock-pattern/src/init.py", line 192, in <module>
    fn_dict[key](sym, df, pivots)
  File "/Users/saurabhgarg/shivshakti/stock-pattern/src/utils.py", line 341, in findBullishVCP
    if isinstance(a, pd.Series | str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
unsupported operand type(s) for |: 'type' and 'type'
Traceback (most recent call last):
  File "/Users/saurabhgarg/shivshakti/stock-pattern/src/init.py", line 192, in <module>
    fn_dict[key](sym, df, pivots)
  File "/Users/saurabhgarg/shivshakti/stock-pattern/src/utils.py", line 341, in findBullishVCP
    if isinstance(a, pd.Series | str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Do we have any specific requirements ?

Thanks
Saurabh

**Comment by cotton1234** [comment]
I guess issue is in my setup as the same is using older packages.

saurabhgarg@MacBook-Pro src % pip3 list|grep pandas
pandas                   1.5.1
pandas-ta                0.3.99b0

Requirement is latest it seems.

I will modify my python setup and recheck.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
This is an error on my part. The Union type `|` is not supported in Python 3.8. I have not mentioned python compatibility in the README. I will post an update today evening for 3.8 compatibility.

There is a planned release (hopefully tomorrow) that brings major improvements in pattern detection, speed and overall user interface.

**Comment by cotton1234** [comment]
Benny ,I Pulled the new code and the same works fine.
Thanks
