### ISSUE TITLE
Getting error while running the code

### ISSUE THREAD

**Issue by skrroy987** [BennyThadikaran/stock-pattern#45]
Hi Benny,
Thanks for the code.
I am facing this error while running this code in my machine. Please help me in resolving it.
I am also attaching my sample data.
![image](https://github.com/BennyThadikaran/stock-pattern/assets/25501498/5b85799b-43f7-4fce-9b2f-d945b5c95dfc)
[3mindia.csv](https://github.com/user-attachments/files/15541476/3mindia.csv)

**Comment by BennyThadikaran** [comment]
I have attached a file `init-c.txt`. Please rename it to `init-c.py` and place it in the src folder of the project.
**ATTACH FILE:** [init-c.txt](https://github.com/user-attachments/files/15543355/init-c.txt)

![Screenshot from 2024-06-04 11-28-06](https://github.com/BennyThadikaran/stock-pattern/assets/19973418/e1c022f4-1abf-49c0-98a7-5034bde665f3)

Error will be printed with the stock symbol name like below. **Please send me the file for the Stock so i can analyse it further.**

![Screenshot from 2024-06-04 11-37-41](https://github.com/BennyThadikaran/stock-pattern/assets/19973418/e3f8e955-829c-4241-97fa-fe2c81cb7aa3)

**Comment by skrroy987** [comment]
I am getting above error in 3MINDIA and AARON. 
[aaron.csv](https://github.com/user-attachments/files/15567889/aaron.csv)
[3mindia.csv](https://github.com/user-attachments/files/15567888/3mindia.csv)

I am also getting error while saving the pattern image for ABB.
[abb.csv](https://github.com/user-attachments/files/15567902/abb.csv)

![image](https://github.com/BennyThadikaran/stock-pattern/assets/25501498/9802b30d-6428-4d20-9b70-6dfb9fc4c2ba)

**Comment by BennyThadikaran** [comment]
Thanks i will look into this today evening.

Can you check the version you're running? 
`py init.py -v` It should read Version 3.1.1. 

If you're using an older version, update to the latest and run the script again.

Also if you're using EOD2 as your source, try running `src/defs/diagnostics.py` in the EOD repo. It should be able to detect common problems with OHLC data.

**Comment by BennyThadikaran** [comment]
I downloaded the files you provided and run it through. I was unable to reproduce your errors. I also checked your files both visually and via loading it into Pandas. No duplicates, no data type issues. All looks clean to me. 

**Please make sure you updated to the latest version of Stock Patterns and try again.**

![Screenshot from 2024-06-05 21-44-40](https://github.com/BennyThadikaran/stock-pattern/assets/19973418/945edd6f-f936-4af3-98ca-fb478be9faa1)

**Comment by BennyThadikaran** [comment]
I trust this has been resolved for you. If not, you can reopen this issue and let me know.
