### ISSUE TITLE
Auto Fit to Window

### ISSUE THREAD

**Issue by Suresh-py** [BennyThadikaran/stock-pattern#55]
When running chart controls "N" The chart window is not auto adjusting to windows it is random for different tickers. I am clicking the maximum button to fit the chart window properly. Screenshot attached.

![image](https://github.com/user-attachments/assets/1878c34c-4812-4bd6-b420-9e253bf5fd64)

**Comment by BennyThadikaran** [comment]
Tkinter module is the only builtin way to get the screen size without resorting to external dependencies. I avoided the approach because Tkinter is quite large to load for a single function. Also Tkinter is not packaged in some Linux python distributions.

I can conditionally import it on the first run and cache the screen size in the user.json. Conditional imports will affect performance on first run but subsequent runs will be smooth.

If Tkinter is not available, it will default to the old behavior and the user will be recommended to install Tkinter (only on first run).

Give me a day or two, I will provide a fix for this. :smiley:

**Comment by BennyThadikaran** [comment]
Please update your repo and let me know if its working for you. I am closing this issue for timebeing

**Comment by Suresh-py** [comment]
I tried with the latest code and it is not working for me. I am using Python Ver 3.12.5

**Comment by BennyThadikaran** [comment]
Can you open `user.json` and confirm if you see `SCREEN_SIZE`.

Did you notice any change in the window size?

Also just curious, what sort of display do you have? 24 inch Desktop or 15 inch laptop etc.

**Comment by BennyThadikaran** [comment]
Ok this is clearly wrong. I use a 15 Inch laptop display and my screen size also shows 14, 8.

As a temporary fix, you can edit the `SCREEN_SIZE` in user.json. (14 is the width and 8 is the height). Adjust till it fits your screen.

Meanwhile I'll see what can be done to fix it.

**Comment by Suresh-py** [comment]
[Recording 2024-08-29 125753.zip](https://github.com/user-attachments/files/16795353/Recording.2024-08-29.125753.zip)
Please see this screen recording if it helps in understanding the problem. I tried with smaller size 10,10. Size of the chart window is reduced but it is still randomly moving across the desktop screen when i move to next tickers using "N". 
Thank you for the support

**Comment by BennyThadikaran** [comment]
Another option, you can set the figscale higher.

To change this, 

1. Open `src/Plotter.py` in any text editor and search for `figscale`. You will find something like below

![Screenshot_2024-08-30_10-37-26](https://github.com/user-attachments/assets/d7beba69-cdca-4e43-8138-57a377531c3f)

> `self.plot_args["figscale"] = 2`

2. Change the value from 2 to a higher number like 4 and save the file.
3. Finally, edit `user.json` and set the `SCREEN_SIZE` to `false`.

```json
{
    "SCREEN_SIZE": false,
}
```

Run the program. Ideally you should notice the window size larger than before. If its still not maximized, you may want to increase the `figscale` even further. This will increase the height of the chart 4x the default while maintaining aspect ratio.

From [Mplfinance docs,](https://github.com/matplotlib/mplfinance/blob/master/examples/plot_customizations.ipynb)

> figscale=1.0 means that the height of the plot will be the default height (see below);
     the width of the plot will depend upon the aspect ratio.

**Comment by BennyThadikaran** [comment]
Ignore my previous comments. I tested on Windows and found a permanent fix to the problem.

`plt.get_current_fig_manager().window.state('zoomed')`

I'm not sure if its specific to Windows OS so need to test and make sure its cross platform. I release the update once I've tested it.

**Comment by BennyThadikaran** [comment]
I have fixed this now. I used the `plt.get_current_fig_manager().full_screen_toggle()`. This puts the window in **full-screen mode** (not maximized state). `full_screen_toggle` is part of Matplotlib backend api and should be stable across all backends. 

`plt.get_current_fig_manager().window.state('zoomed')` also works but is specific to TkAgg backend. If a different backend is in use, it will throw an error which would then have to be handled with backend specific code.

> **To toggle in/out of fullscreen mode, just press `f` key on the chart.**

Let me know if all works well for you. 

And thanks for raising this issue. I'm sure all users will benefit from this change. :+1:

**Comment by Suresh-py** [comment]
In the latest version full screen is stable but the control keys are not working until I make the window active by selecting it with the  mouse. If I don't select the window with the mouse then "N" Is not showing next scrip.

PS: I am using Windows 11

Thank you

**Comment by BennyThadikaran** [comment]
This seems to be a windows specific issue. For windows, if using tkAgg backend it will maximize the window. For any other backend, it will fallback to full-screen mode.

I suppose, tkAgg is the default backend for Matplotlib. If anyone faces issues, I can add additional fallbacks.

```python
if "win" in sys.platform:
    try:
        # Only works with tkAgg backend
        window_manager.window.state("zoomed")
    except AttributeError:
        window_manager.full_screen_toggle()
else:
    window_manager.full_screen_toggle()
```

For now, I have tested on Windows and Linux and its working well.

**Comment by Suresh-py** [comment]
The issue is solved now and thank you
