### ISSUE TITLE
Keep getting file not found

### ISSUE THREAD

**Issue by loccheese** [BennyThadikaran/stock-pattern#75]
I do everything as you said and still getting this error, please help. Thank you so much.
![Screenshot 2024-10-06 014010](https://github.com/user-attachments/assets/53cde55b-cf88-4187-9189-0f9e830bc38f)
Here is my csv file : 
[vcgvnd.csv](https://github.com/user-attachments/files/17267139/vcgvnd.csv)

**Comment by BennyThadikaran** [comment]
Thats happening because you're passing an OHLC file as your watchlist. 

The watchlist must be a list of symbol names one on each line. The symbol names must match the files in your OHLC data folder.

So for vgcvnd.csv you add `vgcvng` to your watchlist file. 

Hope that helps.


Regards,
Benny Thadikaran

**Comment by loccheese** [comment]
> Thats happening because you're passing an OHLC file as your watchlist. The watchlist must be a list of symbol names one on each line. The symbol names must match the files in your OHLC data folder. So for vgcvnd.csv you add `vgcvng` to your watchlist file. Hope that helps. Regards, Benny Thadikaran

i added the name in the watchlist file exactly the way you said before because i have read some previous closed issues but it still not working, here is my user.json and symlist file:
![Screenshot 2024-10-06 132606](https://github.com/user-attachments/assets/bf74fdf8-ac15-4152-81f6-0edbd8cb977a)
Thank you so much!

**Comment by BennyThadikaran** [comment]
First things, I assume `vcgvnd.csv` is located in the `C:/Users/Admin` and I assume your file paths are correct.

Your OHLC file and user.json looks fine. What is the error you're getting?

Adding a watchlist is optional. For one or two symbols, you can just use `py init.py --sym vcgvnd`

With a default watchlist, you can run it as `py init.py`

**Comment by loccheese** [comment]
> First things, I assume `vcgvnd.csv` is located in the `C:/Users/Admin` and I assume your file paths are correct.
> 
> Your OHLC file and user.json looks fine. What is the error you're getting?
> 
> Adding a watchlist is optional. For one or two symbols, you can just use `py init.py --sym vcgvnd`
> 
> With a default watchlist, you can run it as  `py init.py`

When i run `py init.py --sym vcgvnd` and `py init.py` , it show this :
![Screenshot 2024-10-06 142459](https://github.com/user-attachments/assets/1cfa86c5-0267-48d5-9530-d60107b07232)
can  you tell me what is the problem , TYSM!

**Comment by BennyThadikaran** [comment]
Check the version you're running with `py init.py -v`. It should read `Version 3.2.2` else get it updated.

The actual issue is an assertion error. Pandas is unable to parse the Date column format.

I will sit on it tomorrow and figure out a solution for this. Thanks for bringing this up. Where are you sourcing this data from?
```
SYMBOL name: vcgvnd
Traceback (most recent call last):
  File "/home/benny/Documents/python/stock-pattern/src/init.py", line 111, in scan_pattern
    result = fn(sym, df, pivots)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/benny/Documents/python/stock-pattern/src/utils.py", line 431, in find_bullish_vcp
    assert isinstance(pivots.index, pd.DatetimeIndex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

As you can see below the Index is an Object. It should be a DatetimeIndex
```
Index(['16/2/2024', '19/2/2024', '20/2/2024', '21/2/2024', '22/2/2024',
       '23/2/2024', '26/2/2024', '27/2/2024', '28/2/2024', '29/2/2024',
       ...
       '23/9/2024', '24/9/2024', '25/9/2024', '26/9/2024', '27/9/2024',
       '30/9/2024', '1/10/2024', '2/10/2024', '3/10/2024', '4/10/2024'],
      dtype='object', name='Date', length=160)

```

**Comment by loccheese** [comment]
i got the source from: "https://simplize.vn/co-phieu/VCG/lich-su-gia" and download it as an excel file , i sort the date from oldest to newest and do some correction with excel , and then save as a csv file with excel.The version of the py innit is fine. Thank you so much for seeking this issue.

**Comment by loccheese** [comment]
> i got the source from: "https://simplize.vn/co-phieu/VCG/lich-su-gia" and download it as an excel file , i sort the date from oldest to newest and do some correction with excel , and then save as a csv file with excel.The version of the py innit is fine. Thank you so much for handeling this issue.

**Comment by BennyThadikaran** [comment]
You seem well versed with python, so as a temporary fix you need to format the dates as `YYYY-MM-DD` while processing your CSV files. This format is recognized by pandas.

In pandas, you can do it as 

`df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')`

I fix this tomorrow perhaps add a optional custom date format in user.json


Regards,
Benny Thadikaran

**Comment by loccheese** [comment]
> You seem well versed with python, so as a temporary fix you need to format the dates as `YYYY-MM-DD` while processing your CSV files. This format is recognized by pandas. In pandas, you can do it as `df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')` I fix this tomorrow perhaps add a optional custom date format in user.json Regards, 
Benny Thadikaran
Thank you.

**Comment by loccheese** [comment]
> You seem well versed with python, so as a temporary fix you need to format the dates as `YYYY-MM-DD` while processing your CSV files. This format is recognized by pandas. In pandas, you can do it as `df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')` I fix this tomorrow perhaps add a optional custom date format in user.json Regards, Benny Thadikaran

Thank you

**Comment by loccheese** [comment]
Hey, i have run the code success after fix the date format but i ran into this problem:
![Screenshot 2024-10-06 200931](https://github.com/user-attachments/assets/0e68c17d-aa25-4c03-8e01-d06695fbce3a)
i rechecked the file and it was fine , the number in Volume column is the same as OHLC column.
Thank you for your time

**Comment by BennyThadikaran** [comment]
The volume column has an invalid number format (Notice the double dots) -  `5.191.800`

I'm not sure how to interpret this. Perhaps it was meant to be a separator. So 5,191,800 but then there are also numbers like 251.7 which is pretty tiny compared. 

You will need to perform some clean up on the number formatting. This is a problem with the underlying data not something i will be able to correct.

Pandas is treating it as a generic string object.
```
Open      float64
High      float64
Low       float64
Close     float64
Volume     object
```

**Comment by BennyThadikaran** [comment]
I have fixed the issue with date format. You can now add `DATE_FORMAT` in user.json.

```json
{
  "DATA_PATH": "/home/benny/Desktop",
  "LOADER": "EODFileLoader",
  "DEFAULT_TF": "daily",
  "SYM_LIST": "/home/benny/Documents/python/stock-pattern/src/data.csv",
  "DATE_FORMAT": "%d/%m/%Y"
}
```

This will apply to all scans by default. Use custom config if you want to apply the date format to a select group of files.

**To do this:**
1. Create a separate json similar to the above with name of your choice.
2. Pass the config file while running your scans with `py init.py -c custom_config.json`

As for the Volume column you will have to figure this out. Try other sources like yfinance and compare it.

**Comment by loccheese** [comment]
> I have fixed the issue with date format. You can now add `DATE_FORMAT` in user.json.
> 
> ```json
> {
>   "DATA_PATH": "/home/benny/Desktop",
>   "LOADER": "EODFileLoader",
>   "DEFAULT_TF": "daily",
>   "SYM_LIST": "/home/benny/Documents/python/stock-pattern/src/data.csv",
>   "DATE_FORMAT": "%d/%m/%Y"
> }
> ```
> 
> This will apply to all scans by default. Use custom config if you want to apply the date format to a select group of files.
> 
> **To do this:**
> 
> 1. Create a separate json similar to the above with name of your choice.
> 2. Pass the config file while running your scans with `py init.py -c custom_config.json`
> 
> As for the Volume column you will have to figure this out. Try other sources like yfinance and compare it.

i keep getting this :
![Screenshot 2024-10-07 224005](https://github.com/user-attachments/assets/d2a30462-81e3-417c-be05-f43e9559d33f)
even though i had all the files updated.

**Comment by BennyThadikaran** [comment]
Oh I got it. Threads in Windows work differently than Linux. In Windows, threads don't have access to outside variables. They have to be passed passed or defined explicitly.

Pushing a fix. Thanks! Your issue helped solve a couple bugs :smiley:

**Comment by loccheese** [comment]
> Oh I got it. Threads in Windows work differently than Linux. In Windows, threads don't have access to outside variables. They have to be passed passed or defined explicitly.
> 
> Pushing a fix. Thanks! Your issue helped solve a couple bugs 😃

Oh i see it now. Thank you very much for you time! :)

**Comment by BennyThadikaran** [comment]
Its fixed. You will still get the AttributeError. Since the Volume is interpreted as a string and you're trying to access the iloc method on it.

Here is a CSV file that has a pattern. Try it out to confirm all is well.
[olectra.csv](https://github.com/user-attachments/files/17282738/olectra.csv)

**Comment by loccheese** [comment]
> Its fixed. You will still get the AttributeError. Since the Volume is interpreted as a string and you're trying to access the iloc method on it.
> 
> Here is a CSV file that has a pattern. Try it out to confirm all is well. [olectra.csv](https://github.com/user-attachments/files/17282738/olectra.csv)

It is working now, Thank you so much for your time.
