### ISSUE TITLE
How to get data to scan the pattern

### ISSUE THREAD

**Issue by sujeetk789** [BennyThadikaran/stock-pattern#83]
I had downloaded symbol list (which is Nifty 200) but how to download the data as per the timeframe selected? So that the code will scan the symbols and show the pattern.

**Comment by BennyThadikaran** [comment]
You need to have a folder that contains all your ohlc data in csv format. 

The easiest option is to install EOD2. 
<https://github.com/BennyThadikaran/eod2>

Install instructions for EOD2
<https://github.com/BennyThadikaran/eod2/wiki/Installation>

Once EOD2 is setup, your csv data will be located in `src/eod2_data/daily/`

Set `DATA_PATH` in your user.json to the full filepath to the daily folder. 

Hope that helps. 

There is lots of documentation for both EOD2 and Stock-Patterns in the respective wiki. Make sure to go thru them.



On 3 November 2024 13:17:32 UTC, sujeetk789 ***@***.***> wrote:
>I had downloaded symbol list (which is Nifty 200) but how to download the data as per the timeframe selected? So that the code will scan the symbols and show the pattern.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/BennyThadikaran/stock-pattern/issues/83
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>
Regards,
Benny Thadikaran

**Comment by sujeetk789** [comment]
Thanks. Can you please add the open interest or if possible can you create a separate code to fetch historical data which have open interest, volume, open, high, low, close price, 52 wk high, 52 wk low, RSI. It will help to analyze more accurately. Thanks
